### ISSUE TITLE
I get this error on Mac

### ISSUE THREAD

**Issue by LordRatte** [PhaestusFox/void-a-nomicon#1]
![image](https://user-images.githubusercontent.com/8794574/187159228-734671bf-eec5-43bf-8f5f-65965ea78d60.png)

**Comment by PhaestusFox** [comment]
can you make sure the assets folder and game are in the same folder? I have changed this from unwrap to open or default.
but I feel this means I don't know how mac file system works so non or the recipes or items will load.

**Comment by LordRatte** [comment]
I had similar issues with my game as a result of it packaging the whole thing into a dmg image. My solution was to turn it into a tar archive instead. I think part of the problem is that it makes the working directory read-only.

You're welcome to see how I modified it on mine: https://github.com/LordRatte/Flocked-and-Loaded/blob/master/.github/workflows/release.yaml

**Comment by LordRatte** [comment]
So I had a look in the code and I suspect the problem is that you are using a relative path "./assets/ui.config" which may not relative from the binary when you launching the app as a dmg. If this is the case it will also be fixable by shipping your app in an archive.

Worth a try.

**Comment by PhaestusFox** [comment]
wouldn't have thought read only would cause it to fail there, but I definitely think the relative path is what is breaking it, hope just coping and pasting your changes to make it a tar works. I have little to no experience using a mac

**Comment by LordRatte** [comment]
Nice. That seems to work fine. Keep in mind that people have to run the app from the same directory as the binary. Most people will but a terminal user might use/a/path/to/the/app/void-a-nomicon which won't work.

I look forward to your next devlog and wish you success in the competition. Godspeed.
